### ISSUE TITLE
Issues with bin->hex conversion

### ISSUE THREAD

**Issue by DrSchottky** [DigitalSecurity/nrf5x-tools#2]
Hi,
I started playing with this tool and I found two problems with .bin FWs:

- .hex SDs have empty sections (e.g 0x7C0-0xFFF) that are filled with 0xFF in .bin FWs, so objdump generates a different file. Stripping padding lines  from MBR space should be fine.

- .hex SDs start with ":020000040000FA"

O.T.:

- [ Is it supposed to be commented?](https://github.com/DigitalSecurity/nrf5x-tools/blob/ca72860ed186ee6d510340fdadcd787714b1de5f/nrfparse.py#L553)

- Why don't you use SDs' IDs instead of hashes/strings?

**Comment by lychnis42** [comment]
Hi, 
Thank you for your request. 

- The MBR's size is 0x7C0 and the bytes between 0x7C0-0xFFF are reserved and can contain either 0x00 or 0xFF in the .bin FWs, which can confuse the identification, since the signatures become different. 
I fixed that by basing the identification on the signature of the FW's .bin format starting from the byte 0x1000 of the SD.  It seems to be working fine !

- The session.commit() was temporarily commented and I changed it back. 

- What do you mean by SD's IDs ? Do you mean the SDs' IDs in the database or something else ?

**Comment by lychnis42** [comment]
Hi,
Thank you for the issue !

- The MBR's size is 0x7C0 and the bytes between 0x7C0-0xFFF are reserved and can contain either 0x00 or 0xFF in the .bin FWs, which can confuse the identification, since the signatures become different.
I fixed that by basing the identification on the signature of the FW's .bin format starting from the byte 0x1000 of the SD, skipping the MBR section. It seems to be working fine !

- The session.commit() was temporarily commented and I changed it back.

- What do you mean by SD's IDs ? Do you mean the SDs' IDs in the database or something else ?
